on:
  workflow_call:

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.1
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0

      - uses: ./.github/actions/setup-node

      - name: Create Project
        id: createProject
        uses: ./
        with:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Run tests
        run: |
          npm install && npm run test:coverage
